### ISSUE TITLE
Add server load maybe?

### ISSUE THREAD

**Issue by neamtua** [stefanbc/uptimey#6]
http://www.php.net//manual/en/function.sys-getloadavg.php

**Comment by arnisp** [comment]
I would like to do this and make pull request, but first @stefanbc should merge dev branch to master. There are heavy changes.

**Comment by stefanbc** [comment]
@arnisp Thx for trying to help with this. At the moment there is an issue on the dev branch with the conversion to coffescript and thus the app does not work properly. Once that issues is fixed I'll merge into master. :+1:

**Comment by arnisp** [comment]
Ok @stefanbc, will keep following and will join in then.

Although I don't have much experience with coffescript, let me know if I can help with problems.
